"""Add role column to user

Revision ID: 843dfdd16fae
Revises: 
Create Date: 2025-08-27 10:02:21.728349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843dfdd16fae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('course_pkey'))
    )
    # ### end Alembic commands ###
