"""add login history

Revision ID: 01cfa35ab240
Revises: f1967a420270
Create Date: 2025-09-02 14:40:52.842354

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta

# revision identifiers, used by Alembic.
revision = '01cfa35ab240'
down_revision = 'f1967a420270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('login_history_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('login_history_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
