"""Add password_hash to techers

Revision ID: 23eca780071c
Revises: 01cfa35ab240
Create Date: 2025-09-08 11:19:25.956726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23eca780071c'
down_revision = '01cfa35ab240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
