"""Add missing columns to user table

Revision ID: 6577088e9a75
Revises: 5442f808d2b8
Create Date: 2025-09-02 14:10:30.387232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime, timedelta
# revision identifiers, used by Alembic.
revision = '6577088e9a75'
down_revision = '5442f808d2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('login_time')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initials', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('guardian_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('guardian_number')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('address')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('initials')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###
