"""Add profile_picture to Techer

Revision ID: a76059b030d1
Revises: a55b8f8f8a33
Create Date: 2025-09-08 13:53:53.822997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76059b030d1'
down_revision = 'a55b8f8f8a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
