"""Add reset_code fields to User

Revision ID: b58a58711d3e
Revises: 33717be235f9
Create Date: 2025-09-18 13:27:38.765700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58a58711d3e'
down_revision = '33717be235f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('techers')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiry')
        batch_op.drop_column('reset_code')

    op.create_table('techers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lecturer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('rate_per_hour', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('no_of_hours_allocated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('techers_pkey')),
    sa.UniqueConstraint('username', name=op.f('techers_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
